### ISSUE TITLE
Distance value, Lux value

### ISSUE THREAD

**Issue by grbrbr** [DominikBer123/Red-pitaya#1]
Distance: Read from the right register instead of 0.
Light: is the output in lux???

**Comment by LizzardDog** [comment]
Light: From documentation for mode 0001_0000: How to calculate when the data High Byte is "10000011" and Low Byte is "10010000"
 ( 2^15 + 2^9 + 2^8 + 2^7 + 2^4) / 1.2 ≒ 28067 [ lx ]
